### ISSUE TITLE
Rate function not available

### ISSUE THREAD

**Issue by tahseenjamal** [razorpay/go-financial#27]
It seems that the Rate function has been removed as it doesn't work throwing error that Rate not available

**Comment by gyanesh-m** [comment]
Rate function exists but it's not available since it was not released. Will do. Thanks!

**Comment by gyanesh-m** [comment]
@tahseenjamal its resolved now.
There is some error in the example will update it. You can try the following:
```go
package main

import (
	"fmt"

	gofinancial "github.com/razorpay/go-financial"
	"github.com/razorpay/go-financial/enums/paymentperiod"
	"github.com/shopspring/decimal"
)

func main() {
	fv := decimal.NewFromFloat(-3000)
	pmt := decimal.NewFromFloat(100)
	pv := decimal.NewFromFloat(2000)
	when := paymentperiod.BEGINNING
	nper := int64(4)
	maxIter := int64(100)
	tolerance := decimal.NewFromFloat(1e-6)
	initialGuess := decimal.NewFromFloat(0.1)

	rate, err := gofinancial.Rate(pv, fv, pmt, nper, when, maxIter, tolerance, initialGuess)
	if err != nil {
		fmt.Printf("error",err.Error())
	} else {
		fmt.Printf("rate: %v ", rate)
	}
  fmt.Printf("done")
	// Output:
	// rate: 0.06106257989825202
}
```

**Comment by tahseenjamal** [comment]
@gyanesh-m Worked. Thanks

Actually, I asked because I have also written same function in C long back using Newton Raphson. But instead of simple initial guess, I use a derived computation value as initial guess that makes result accurate in lesser time and avoid any borderline cases, which can leave iteration in loop or incorrect answer
