### ISSUE TITLE
replace float

### ISSUE THREAD

**Issue by gyanesh-m** [razorpay/go-financial#7]
After the post on [reddit](https://www.reddit.com/r/golang/comments/l4x9zs/introducing_gofinancial/gkrg0s4/), we got some really good feedback on not using float for this project.
There were quite a few good options which came up in the discussion, they were as follows:
1. **Use arbitrary-precision fixed-point decimal**
https://github.com/shopspring/decimal

2. **Use decimal.Big:**
https://gist.github.com/teepark/35e19b359ae670ebcf715d16c8f40282
This uses [github.com/ericlagergren/decimal ](https://github.com/ericlagergren/decimal), which is another arbitrary precision pkg in go.
3. **Use golang's math/big.Int**
https://golang.org/pkg/math/big/
4. **Use golang's math/big.Rat**
https://golang.org/pkg/math/big/

We are going forward with 1st approach because of its simpler API when compared to 3.

**Comment by gedw99** [comment]
I use this 


https://github.com/Rhymond/go-money

**Comment by gyanesh-m** [comment]
@gedw99 this won't be usable here because we need power() operation which is not supported in go-money pkg. The outputs from go-financial will be int64. You can use them to construct go-money objects.

**Comment by gyanesh-m** [comment]
Closing this issue. This is now supported in release v1.0.0
